### PR TITLE
Updates to app inventor for FTC_SDK v3.1.

### PR DESCRIPTION
**Pull request by lizlooney**
@ftctechnh

### CODE REVIEW

**Comment by ftctechnh** [comment]
@lizlooney 
Hi Liz - I had an interesting bug.  I was writing some simple op modes and wanted to use the telemetry block to send the motor power info to be displayed on the driver station.  I dragged a telemetry (numeric) block onto the design area in the Blocks mode of App Inventor.  the weird thing was that it stayed there.  I could drag off of that block and move the telemetry block to where i wanted, but a copy of the telemetry block always persisted in the location where I originally placed it.

I could not delete or drag this persistent block away.  

here is a video that shows what happened if I tried to move or delete the persistent block:

https://drive.google.com/open?id=0B_7ZNztySlZhQXhzTkV3eHJQczg

Eventually, I got rid of this persistent block.  I think what I had to do was move the design area around (I clicked on the area and pulled it with the mouse).  Once I was in a different view, I was trying to delete the persistent block and it disappeared finally when I deleted it.

I'm not sure if this is an App Inventor issue or an FTC app inventor issue, but I cannot recreate the problem yet.

**Comment by lizlooney** [comment]
Yikes. I'd like to know how that happened. The status at the bottom of the workspace says there are 19 warnings. Are there 19 of those blocks, rather than infinite?
Do you happen to have a saved copy of the project in that state that I can look at?

Do you think that somehow the block(s) got there by something funky with the mouse events when you were trying to drag the block from the toolbox?

**Comment by ftctechnh** [comment]
Hi Liz,

Maybe I just had 19 blocks stacked on top of each other?  However, I don't think so... It seemed like an awful (unlimited) amount of blocks.  I think I did do some weird thing with the mouse as I was selecting that particular block from the menu.  It got placed onto the design area and just stayed there.  

I attached a copy of the project file (change .txt to .aia).
[TomTestAI.txt](https://github.com/FIRST-Tech-Challenge/appinventor-sources/files/1028925/TomTestAI.txt)

**Comment by ftctechnh** [comment]
Liz - It happened again.  It looks like it pastes a large number (over 50 this time) of a block onto the design area.  It seems like it's blocks that are associated with the FtcRobotController widget.

https://drive.google.com/open?id=0B_7ZNztySlZhVlJpRGxPZDVKOXM

Do you want me to share my VirtualBox appliance?

**Comment by ftctechnh** [comment]
@lizlooney 
Hi Liz,

It happened again.  This time when I was using the  gravity block from the Bosch IMU set of blocks.  I got 78 copies of the block when I selected it from the palette.

**Comment by ftctechnh** [comment]
Here's my project with my updated op mode (I cleaned up the IMU code to make it work better and actually display the correct info).
[TomTestAI.txt](https://github.com/FIRST-Tech-Challenge/appinventor-sources/files/1029191/TomTestAI.txt)

**Pull request merged**
