### PR TITLE
Add support for LynxI2cColorRangeSensor

### PR DESCRIPTION
**Pull request by lizlooney**
@ftctechnh 

I hope this fixes the problem you saw where dragging out a block sometimes resulted in many blocks being added to the workspace.

### CODE REVIEW

**Comment by lizlooney** [comment]
I think you have to do a "git submodule update" in order to pull in the changes from https://github.com/mit-cml/blockly.

**Comment by lizlooney** [comment]
This brings in code from MIT release nb157.
According to [MIT's release notes](http://appinventor.mit.edu/ai2/ReleaseNotes.html), they have fixed the bug where sometimes you would get 20+ blocks when you dragged a block out of the blocks drawer.

**Comment by lizlooney** [comment]
This brings in code from MIT release nb158.

**Comment by ftctechnh** [comment]
Hi Liz - I initially had issues building the blockly related code.  To fix the problem, I had to do the following:

1. When I cloned the code I used "git clone --depth=1 --recursive https://github.com/FIRST-Tech-Challenge/appinventor-sources.git".  I specified a depth of 1 to save space.  I did the recursive argument to ensure that it would get any submodules.

2. After I cloned the repo, I did a "git submodule update --init --recursive" to make sure the submodules were up to date (i assume only the Blockly subfolder is a submodule).

This seemed to work and I was able to build the app inventor without issue.

**Pull request merged**
